name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Build_and_Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }} | docker login -u mcatwj --password-stdin
    - name: Build the Docker image
      run: ./bin/docker.sh build
    - name: Deploy the Docker image
      run: ./bin/docker.sh deploy
